pipeline {
    agent any
    stages {
        stage('Build') { 
            steps {
                sh 'npm cache clean --force'
                sh 'rm -rf node_modules'
                sh 'npm install' 
                sh 'npm run build'
                echo "now building..."
            }
        }
    }
}