pipeline {
    agent any
    stages {
        stage('Build') { 
            steps {
                sh 'curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash'
                sh 'export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm'
                sh 'nvm install v12'
                sh 'nvm use v12'
                sh 'npm -v'
                sh 'node -v'
                sh 'npm install'
                sh 'npm run build'
                echo "building..."
            }
        }
    }
}